site_name: Web learn

theme:
  name: material
  features:
    - navigation.top
    - search.highlight
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: "#"
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: index.md
  - HTML/CSS:
    - HTML: html_css/html.md
    - CSS: html_css/css.md
    - HTTP协议: html_css/http.md
    - Bootstrap3: html_css/bootstrap.md
  - JavaScript:
    - JavaScript: js/js.md
    - Promise: js/promise.md
    - axios: js/axios.md
    - Node.js: js/nodejs.md
    - Webpack: js/webpack.md
    - TypeScript: js/typescript.md
    - jQuery: js/jquery.md
    - Vue.js: js/Vue.md
    - 编程题: js/programming.md
    - ElementUI: js/element.md
    - Quasar: js/quasar.md
    - 数据可视化:
      - 数据可视化: js/visualization.md
      - Echarts(基本图): js/echarts.md
      - amCharts(地图): js/amcharts.md
      - plotly.js(小提琴图): js/plotly.md
      - Highcharts(基因结构图): js/highcharts.md
      - Phylotree.js(绘制进化树): js/phylotree.md
      - Cytoscape.js(网络图): js/cytoscape.md
      - gtex-viz(带聚类树的热图): js/gtex_viz.md
      - BioCircos.js(eQTL的circos图): js/biocircos.md
  - PHP:
    - PHP: php/php.md
    - ThinkPHP: php/tp.md
  - Database:
    - MySQL: db/mysql.md
    - MongoDB: db/mongodb.md
  - Linux: linux/linux.md
  - More: 
    - 异常检测、提交反馈: more/user_inter.md
    - JBrowse1: more/jbrowse1.md
    - JBrowse2: more/jbrowse2.md
    - Blast: more/blast.md
    - GBrowse_syn: more/gbrowse.md

extra_css:
  - stylesheets/extra.css